trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'sc-azure-dineshdemo'
  resourceGroup: 'rg-dineshdemo'
  acrName: 'dineshdemoacr'
  acrLoginServer: 'dineshdemoacr.azurecr.io'
  aksName: 'DineshDemo'
  imageName: 'bus-service'
  bicepFile: 'infra/aks-dineshdemo.bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
# 1) Build & Push image
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    steps:
    - task: Checkout@1
      displayName: 'Checkout'

    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: Docker@2
      displayName: 'Build and Push bus-service image'
      inputs:
        containerRegistry: '$(azureSubscription)'   # uses Azure service connection
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'BusService/Dockerfile'
        tags: |
          $(Build.BuildId)

# 2) Deploy AKS via Bicep
- stage: DeployInfra
  displayName: Deploy AKS Infra
  dependsOn: Build
  jobs:
  - job: DeployInfra
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy AKS Bicep'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroup) \
            --template-file $(bicepFile) \
            --parameters aksName=$(aksName) acrName=$(acrName)

# 3) Deploy Namespace + App to AKS
- stage: DeployApp
  displayName: Deploy bus-service to AKS
  dependsOn: DeployInfra
  jobs:
  - job: DeployApp
    steps:
    - task: AzureCLI@2
      displayName: 'Get AKS credentials'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials \
            --resource-group $(resourceGroup) \
            --name $(aksName) \
            --overwrite-existing

          kubectl apply -f k8s/namespace-dineshdemo.yaml
          # Replace image tag in manifest and apply
          sed "s/\$(Build.BuildId)/$(Build.BuildId)/g" k8s/bus-service.yaml | kubectl apply -f -
