apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: booking-pubsub
  namespace: dineshdemo
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-conn
        key: connectionString
  scopes:
    - bus-service
